### ISSUE TITLE
FE: Connect feedback template backend to frontend [S]

### ISSUE THREAD

**Issue by smithj11** [oci-labs/check-ins#1214] opened 2021-07-15 14:55 UTC
- [ ] Add API call to feedback template get endpoint to get default template
- [ ] Create function on FeedbackTemplateSelector component that calls and handles data from the API 
- [ ] Replace dummy templates (excluding ad-hoc button) by mapping actual data returned from API to the templates stored in the component
- [ ] Perform different user interactions like going back from following stops, refreshing, etc. to ensure that the template is consistently displayed
- [ ] Ensure that questions are displayed in template preview when clicking on default template
- [ ] Cypress testing (?)

Dependent on: 1167 (refactored backend), 1211 (default volume change)

**Comment by sagetheherb** [comment] 2021-07-22 14:30
is is a duplicate of #1246

**Closed by sagetheherb** 2021-07-22 14:30 UTC
Labels: duplicate, feedback request, web-ui
