### ISSUE TITLE
FE: URL validation that redirects appropriately (S)

### ISSUE THREAD

**Issue by smithj11** [oci-labs/check-ins#1056] opened 2021-06-21 22:02 UTC
- [ ] If user has URL query information appropriate for current step, redirect the user to the step they last left off on.
- [ ] If user goes directly to a step without providing appropriate parameters for each step (i.e. recipients for Step 2, template for Step 3, etc.) redirect user to step 1.
- [ ] User must not be able to process to the next page of stepper prior to completing the current page.
- [ ]  snapshots are implemented/updated.

**Comment by pieperm** [comment] 2021-06-23 21:07
Duplicate of issue #1057

**Closed by pieperm** 2021-06-23 21:07 UTC
Labels: duplicate, feedback request, web-ui
