### ISSUE TITLE
BE > validations for checkins 

### ISSUE THREAD

**Issue by bhatiam12** [oci-labs/check-ins#223] opened 2020-08-24 15:59 UTC
Need to discuss how we need to handle checkins from PDLs, Please see the note below from Chris. Opening this as a placeholder and will be discussed in backlog grooming. 

```
Can only PDLs create checkins? Also at some point we will need to discuss blocking people from doing some action x on behalf of someone else, even though their role may give them access to do it. An example of that being here, a PDL creating a checkin for a member who they are not the PDL of.

@mkimberlin Should those be different stories?```

**Comment by Bagurp** [comment] 2020-09-03 15:15
Closing this issue since a duplicate of this has been opened -
https://github.com/oci-labs/check-ins/issues/245

**Closed by Bagurp** 2020-09-03 15:15 UTC
