### ISSUE TITLE
BE: Implement feedback request services [M]

### ISSUE THREAD

**Issue by smithj11** [oci-labs/check-ins#1012] opened 2021-06-14 15:24 UTC
- [x] Implement save function in services implementation
- [x] Implement update function in services implementation
- [x] Implement delete function in services implementation
- [x] Implement getById function in services implementation
- [x] Find by requestee id function in services implementation
- [x] Find by creator id function in services implementation

**Comment by pieperm** [comment] 2021-06-29 14:45
Duplicate of issue #1013

**Closed by pieperm** 2021-06-29 14:46 UTC
Labels: duplicate, feedback request, server
